import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import NavBar from "@/components/NavBar"; // NavBar is now imported in ConditionalNavBar
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
// import { initializeApp } from "firebase/app"; // This import is not used here and can be removed
import { AuthProvider /* Removed useAuth */ } from "@/context/Authcontext";
import React from "react";
import ConditionalNavBar from "@/components/ConditionalNavBar"; // Import the new client component

// Initialize Firebase (only once)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed ConditionalNavBar component definition from here

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <ConditionalNavBar>{children}</ConditionalNavBar>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
